//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod asset;
pub mod consumable;
pub mod location;
pub mod maintenancelog;
pub mod project;
pub mod transaction;
pub mod user;
