//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::asset::Entity as Asset;
pub use super::consumable::Entity as Consumable;
pub use super::location::Entity as Location;
pub use super::maintenancelog::Entity as Maintenancelog;
pub use super::project::Entity as Project;
pub use super::transaction::Entity as Transaction;
pub use super::user::Entity as User;
