/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as ReportsImport } from './routes/reports'
import { Route as InventoryImport } from './routes/inventory'
import { Route as IndexImport } from './routes/index'
import { Route as InventoryAddImport } from './routes/inventory.add'
import { Route as InventoryAssetIdImport } from './routes/inventory.$assetId'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as DemoTableImport } from './routes/demo/table'
import { Route as DemoStoreImport } from './routes/demo.store'
import { Route as ApiAssetsImport } from './routes/api.assets'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ReportsRoute = ReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRoute,
} as any)

const InventoryRoute = InventoryImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InventoryAddRoute = InventoryAddImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => InventoryRoute,
} as any)

const InventoryAssetIdRoute = InventoryAssetIdImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => InventoryRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const DemoTableRoute = DemoTableImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRoute,
} as any)

const DemoStoreRoute = DemoStoreImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRoute,
} as any)

const ApiAssetsRoute = ApiAssetsImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryImport
      parentRoute: typeof rootRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsImport
      parentRoute: typeof rootRoute
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreImport
      parentRoute: typeof rootRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/inventory/$assetId': {
      id: '/inventory/$assetId'
      path: '/$assetId'
      fullPath: '/inventory/$assetId'
      preLoaderRoute: typeof InventoryAssetIdImport
      parentRoute: typeof InventoryImport
    }
    '/inventory/add': {
      id: '/inventory/add'
      path: '/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof InventoryAddImport
      parentRoute: typeof InventoryImport
    }
  }
}

// Create and export the route tree

interface InventoryRouteChildren {
  InventoryAssetIdRoute: typeof InventoryAssetIdRoute
  InventoryAddRoute: typeof InventoryAddRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryAssetIdRoute: InventoryAssetIdRoute,
  InventoryAddRoute: InventoryAddRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/assets': typeof ApiAssetsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/inventory/$assetId': typeof InventoryAssetIdRoute
  '/inventory/add': typeof InventoryAddRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/assets': typeof ApiAssetsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/inventory/$assetId': typeof InventoryAssetIdRoute
  '/inventory/add': typeof InventoryAddRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/assets': typeof ApiAssetsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/inventory/$assetId': typeof InventoryAssetIdRoute
  '/inventory/add': typeof InventoryAddRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/api/assets'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/inventory/$assetId'
    | '/inventory/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/api/assets'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/inventory/$assetId'
    | '/inventory/add'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/api/assets'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/inventory/$assetId'
    | '/inventory/add'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAssetsRoute: typeof ApiAssetsRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiAssetsRoute: ApiAssetsRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/inventory",
        "/reports",
        "/settings",
        "/api/assets",
        "/demo/store",
        "/demo/table",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/inventory": {
      "filePath": "inventory.tsx",
      "children": [
        "/inventory/$assetId",
        "/inventory/add"
      ]
    },
    "/reports": {
      "filePath": "reports.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/api/assets": {
      "filePath": "api.assets.tsx"
    },
    "/demo/store": {
      "filePath": "demo.store.tsx"
    },
    "/demo/table": {
      "filePath": "demo/table.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/inventory/$assetId": {
      "filePath": "inventory.$assetId.tsx",
      "parent": "/inventory"
    },
    "/inventory/add": {
      "filePath": "inventory.add.tsx",
      "parent": "/inventory"
    }
  }
}
ROUTE_MANIFEST_END */
